// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package googlekeep_clone

type Label struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Todos  []*Todo `gorm:"many2many:todos_labels"`
	UserID string
}

type Note struct {
	ID          string `gorm:"primary_key"`
	TodoID      string `gorm:"primary_key;auto_increment:false"`
	Text        string `json:"text"`
	IsCompleted bool   `json:"isCompleted"`
}

type Todo struct {
	ID             string   `json:"id"`
	Title          string   `json:"title"`
	Notes          []*Note  `json:"notes" gorm:"foreignkey:TodoID"`
	Labels         []*Label `json:"labels" gorm:"many2many:todos_labels"`
	Color          string   `json:"color"`
	IsCheckboxMode bool     `json:"isCheckboxMode"`
	UserID         string
}

type User struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Email    string   `json:"email"`
	ListMode bool     `json:"listMode"`
	DarkMode bool     `json:"darkMode"`
	Todos    []*Todo  `gorm:"foreignkey:UserID"`
	Labels   []*Label `gorm:"foreignkey:UserID"`
}
